package io.github.notablogger.springxpose.processor.generator;

import com.squareup.javapoet.*;
import io.github.notablogger.springxpose.annotation.RelationMode;
import io.github.notablogger.springxpose.processor.model.EntityModel;
import io.github.notablogger.springxpose.processor.model.FieldModel;
import io.github.notablogger.springxpose.processor.model.RelationFieldModel;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates a DTO class for each @ExposeEntity-annotated entity.
 *
 * <p>Rules:
 * <ul>
 *   <li>All scalar fields except those listed in {@code ignoredFields} are included.</li>
 *   <li>OneToMany / ManyToMany (collection) relations are always excluded — eliminates circular refs.</li>
 *   <li>ManyToOne / OneToOne (single) relations:
 *     <ul>
 *       <li>{@code ALWAYS_OBJECT} → full related entity type field</li>
 *       <li>{@code ALWAYS_IDS} or {@code IDS_FOR_LIST_OBJECT_FOR_SINGLE} → Long {@code <field>Id}</li>
 *     </ul>
 *   </li>
 * </ul>
 */
public class DtoGenerator {

    private final ProcessingEnvironment processingEnv;

    public DtoGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    public void generate(EntityModel model) {
        String dtoName = model.entitySimpleName() + "Dto";
        TypeSpec.Builder dto = TypeSpec.classBuilder(dtoName)
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Generated DTO for {@link $L} — do not edit.\n", model.entitySimpleName());

        // Scalar fields (excludes @Id field from ignored check since id is always needed,
        // but respects ignoredFields for everything else)
        for (FieldModel field : model.fields()) {
            if (!field.isId() && model.ignoredFields().contains(field.name())) continue;
            TypeName typeName = resolveTypeName(field.typeName());
            dto.addField(typeName, field.name(), Modifier.PRIVATE);
            dto.addMethod(getter(field.name(), typeName));
            dto.addMethod(setter(field.name(), typeName));
        }

        // Relation fields — only SINGLE (ManyToOne / OneToOne)
        // COLLECTION (OneToMany / ManyToMany) are always skipped
        for (RelationFieldModel rel : model.relations()) {
            if (model.ignoredFields().contains(rel.name())) continue;
            if ("COLLECTION".equals(rel.relationType())) continue; // always skip collections

            if (model.relationMode() == RelationMode.ALWAYS_OBJECT) {
                // Include full related entity type
                ClassName relatedType = ClassName.bestGuess(rel.relatedEntityType());
                dto.addField(relatedType, rel.name(), Modifier.PRIVATE);
                dto.addMethod(getter(rel.name(), relatedType));
                dto.addMethod(setter(rel.name(), relatedType));
            } else {
                // IDS_FOR_LIST_OBJECT_FOR_SINGLE or ALWAYS_IDS → Long <fieldName>Id
                String idFieldName = rel.name() + "Id";
                dto.addField(TypeName.LONG.box(), idFieldName, Modifier.PRIVATE);
                dto.addMethod(getter(idFieldName, TypeName.LONG.box()));
                dto.addMethod(setter(idFieldName, TypeName.LONG.box()));
            }
        }

        try {
            JavaFile.builder(model.packageName() + ".generated", dto.build())
                .addFileComment("Generated by spring-xpose — do not edit")
                .build()
                .writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw new RuntimeException("Failed to write DTO for " + model.entitySimpleName(), e);
        }
    }

    private static TypeName resolveTypeName(String rawTypeName) {
        // Strip inline annotation tokens e.g. "java.lang.@jakarta.validation.constraints.NotBlank String"
        // → "java.lang.String"
        String typeName = rawTypeName.replaceAll("@\\S+\\s*", "").trim();

        return switch (typeName) {
            case "long", "java.lang.Long"       -> TypeName.LONG.box();
            case "int", "java.lang.Integer"      -> TypeName.INT.box();
            case "double", "java.lang.Double"    -> TypeName.DOUBLE.box();
            case "boolean", "java.lang.Boolean"  -> TypeName.BOOLEAN.box();
            case "float", "java.lang.Float"      -> TypeName.FLOAT.box();
            default -> ClassName.bestGuess(typeName);
        };
    }

    private static MethodSpec getter(String name, TypeName type) {
        String prefix = type.equals(TypeName.BOOLEAN.box()) ? "is" : "get";
        return MethodSpec.methodBuilder(prefix + capitalize(name))
            .addModifiers(Modifier.PUBLIC)
            .returns(type)
            .addStatement("return this.$L", name)
            .build();
    }

    private static MethodSpec setter(String name, TypeName type) {
        return MethodSpec.methodBuilder("set" + capitalize(name))
            .addModifiers(Modifier.PUBLIC)
            .addParameter(type, name)
            .addStatement("this.$L = $L", name, name)
            .build();
    }

    private static String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}
