package io.github.notablogger.springxpose.processor.generator;

import com.squareup.javapoet.*;
import io.github.notablogger.springxpose.processor.model.EntityModel;
import io.github.notablogger.springxpose.processor.model.FieldModel;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.Optional;

/**
 * Generates a {@code <Entity>FilterParams} POJO for entities/documents that declare
 * {@code filterableFields}. The POJO is bound from query parameters via
 * {@code @ModelAttribute} in the generated controller's {@code findAll} method.
 *
 * <p>Each filterable field is typed to match the entity field (primitives promoted
 * to their wrapper type so Spring MVC can bind absent params as {@code null}).
 *
 * <p>Example output for {@code @ExposeEntity(filterableFields = {"name", "price"})}:
 * <pre>
 * public class ProductFilterParams {
 *     private String name;
 *     private Double price;
 *     public String getName() { return name; }
 *     public void setName(String name) { this.name = name; }
 *     public Double getPrice() { return price; }
 *     public void setPrice(Double price) { this.price = price; }
 * }
 * </pre>
 */
public class FilterParamsGenerator {

    private final ProcessingEnvironment processingEnv;

    public FilterParamsGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    public void generate(EntityModel model) {
        if (!model.hasFilterableFields()) return;

        String entity = model.entitySimpleName();
        TypeSpec.Builder clazz = TypeSpec.classBuilder(entity + "FilterParams")
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Generated by spring-xpose — do not edit.\n"
                + "Query filter parameters for {@code GET /api/" + model.basePath() + "}.\n"
                + "Bind automatically via {@code @ModelAttribute} — absent params are {@code null} (ignored).\n");

        for (String fieldName : model.filterableFields()) {
            Optional<FieldModel> fm = model.fields().stream()
                .filter(f -> f.name().equals(fieldName))
                .findFirst();

            TypeName fieldType = fm
                .map(f -> toWrapperTypeName(f.typeName()))
                .orElse(ClassName.get(String.class));

            String cap = capitalize(fieldName);

            clazz.addField(FieldSpec.builder(fieldType, fieldName, Modifier.PRIVATE).build());
            clazz.addMethod(MethodSpec.methodBuilder("get" + cap)
                .addModifiers(Modifier.PUBLIC)
                .returns(fieldType)
                .addStatement("return $L", fieldName)
                .build());
            clazz.addMethod(MethodSpec.methodBuilder("set" + cap)
                .addModifiers(Modifier.PUBLIC)
                .returns(TypeName.VOID)
                .addParameter(fieldType, fieldName)
                .addStatement("this.$L = $L", fieldName, fieldName)
                .build());
        }

        try {
            JavaFile.builder(model.packageName() + ".generated", clazz.build())
                .addFileComment("Generated by spring-xpose — do not edit")
                .build()
                .writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw new RuntimeException("Failed to write FilterParams for " + model.entitySimpleName(), e);
        }
    }

    /** Promotes primitive type names to their nullable wrapper counterparts. */
    private static TypeName toWrapperTypeName(String typeName) {
        return switch (typeName) {
            case "long",    "java.lang.Long"      -> ClassName.get("java.lang", "Long");
            case "int",     "java.lang.Integer"   -> ClassName.get("java.lang", "Integer");
            case "double",  "java.lang.Double"    -> ClassName.get("java.lang", "Double");
            case "float",   "java.lang.Float"     -> ClassName.get("java.lang", "Float");
            case "boolean", "java.lang.Boolean"   -> ClassName.get("java.lang", "Boolean");
            case "java.lang.String"               -> ClassName.get("java.lang", "String");
            default                               -> ClassName.bestGuess(typeName);
        };
    }

    private static String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}
