package io.github.notablogger.springxpose.processor.generator;

import com.squareup.javapoet.*;
import io.github.notablogger.springxpose.annotation.RelationMode;
import io.github.notablogger.springxpose.processor.model.EntityModel;
import io.github.notablogger.springxpose.processor.model.RelationFieldModel;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.List;

/**
 * Generates a MapStruct mapper interface for each @ExposeEntity-annotated entity.
 *
 * <p>For ALWAYS_OBJECT relations: MapStruct handles the mapping automatically.
 * For IDS / IDS_FOR_LIST_OBJECT_FOR_SINGLE: generates explicit @Mapping(source="field.id", target="fieldId").
 */
public class MapperGenerator {

    private final ProcessingEnvironment processingEnv;

    public MapperGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    public void generate(EntityModel model) {
        String entity   = model.entitySimpleName();
        String dtoName  = entity + "Dto";
        String mapperName = entity + "Mapper";

        ClassName entityClass  = ClassName.bestGuess(model.entityClassName());
        ClassName dtoClass     = ClassName.get(model.packageName() + ".generated", dtoName);
        ClassName mapperAnnot  = ClassName.get("org.mapstruct", "Mapper");
        ClassName mappingAnnot = ClassName.get("org.mapstruct", "Mapping");
        ClassName listClass    = ClassName.get("java.util", "List");

        // @Mapper(componentModel = "spring")
        AnnotationSpec mapperSpec = AnnotationSpec.builder(mapperAnnot)
            .addMember("componentModel", "$S", "spring")
            .build();

        TypeSpec.Builder mapper = TypeSpec.interfaceBuilder(mapperName)
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Generated MapStruct mapper for {@link $L} → {@link $L} — do not edit.\n",
                entity, dtoName)
            .addAnnotation(mapperSpec);

        // Build toDto method with @Mapping for relation ID fields
        MethodSpec.Builder toDto = MethodSpec.methodBuilder("toDto")
            .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
            .addParameter(entityClass, "entity")
            .returns(dtoClass);

        // For each SINGLE relation that is NOT ALWAYS_OBJECT and NOT ignored,
        // add @Mapping(source = "field.id", target = "fieldId")
        for (RelationFieldModel rel : model.relations()) {
            if ("COLLECTION".equals(rel.relationType())) continue;
            if (model.ignoredFields().contains(rel.name())) continue;

            if (model.relationMode() != RelationMode.ALWAYS_OBJECT) {
                toDto.addAnnotation(AnnotationSpec.builder(mappingAnnot)
                    .addMember("source", "$S", rel.name() + ".id")
                    .addMember("target", "$S", rel.name() + "Id")
                    .build());
            }
        }

        mapper.addMethod(toDto.build());

        // toDtoList — default implementation delegates to toDto
        TypeName entityListType = ParameterizedTypeName.get(listClass, entityClass);
        TypeName dtoListType    = ParameterizedTypeName.get(listClass, dtoClass);
        mapper.addMethod(MethodSpec.methodBuilder("toDtoList")
            .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
            .addParameter(entityListType, "entities")
            .returns(dtoListType)
            .build());

        try {
            JavaFile.builder(model.packageName() + ".generated", mapper.build())
                .addFileComment("Generated by spring-xpose — do not edit")
                .build()
                .writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw new RuntimeException("Failed to write mapper for " + entity, e);
        }
    }
}

