package io.github.notablogger.springxpose.processor.generator;

import com.squareup.javapoet.*;
import io.github.notablogger.springxpose.annotation.StoreType;
import io.github.notablogger.springxpose.processor.model.EntityModel;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates a Spring Data repository interface for each
 * {@code @ExposeEntity}- or {@code @ExposeDocument}-annotated class.
 *
 * <ul>
 *   <li>{@code StoreType.JPA}   → {@code JpaRepository<Entity, Id>}</li>
 *   <li>{@code StoreType.MONGO} → {@code MongoRepository<Entity, Id>}
 *       (used automatically when class carries {@code @ExposeDocument})</li>
 * </ul>
 *
 * <p>Generated output example for {@code Product} (JPA, {@code Long} id):
 * <pre>
 * package com.example.entity.generated;
 *
 * &#64;Repository
 * public interface ProductRepository extends JpaRepository&lt;Product, Long&gt; {}
 * </pre>
 *
 * <p>The generated interface is placed in the same {@code .generated} subpackage
 * as the controller and security configurer, so it is picked up automatically
 * by Spring Data's repository scanning.
 */
public class RepositoryGenerator {

    private final ProcessingEnvironment processingEnv;

    public RepositoryGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    public void generate(EntityModel model) {
        ClassName entityClass = ClassName.bestGuess(model.entityClassName());
        ClassName idClass     = ClassName.bestGuess(model.idClassName());
        ClassName repository  = ClassName.get("org.springframework.stereotype", "Repository");

        // Choose base interface based on store type
        ClassName baseRepository = model.storeType() == StoreType.MONGO
            ? ClassName.get("org.springframework.data.mongodb.repository", "MongoRepository")
            : ClassName.get("org.springframework.data.jpa.repository", "JpaRepository");

        TypeName superInterface = ParameterizedTypeName.get(baseRepository, entityClass, idClass);

        String storeLabel = model.storeType() == StoreType.MONGO ? "MongoDB" : "JPA";

        TypeSpec repoInterface = TypeSpec.interfaceBuilder(model.entitySimpleName() + "Repository")
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Generated by spring-xpose — do not edit.\n"
                + "Spring Data " + storeLabel + " repository for {@link $T}.\n", entityClass)
            .addAnnotation(repository)
            .addSuperinterface(superInterface)
            .build();

        try {
            JavaFile.builder(model.packageName() + ".generated", repoInterface)
                .addFileComment("Generated by spring-xpose — do not edit")
                .build()
                .writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw new RuntimeException(
                "Failed to write repository for " + model.entitySimpleName(), e);
        }
    }
}

