package io.github.notablogger.springxpose.processor.generator;

import com.squareup.javapoet.*;
import io.github.notablogger.springxpose.processor.model.EntityModel;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates a Spring Data {@code JpaRepository} interface for each
 * {@code @ExposeEntity}-annotated class, so users don't have to write it manually.
 *
 * <p>Generated output example for {@code Product} with {@code Long} id:
 * <pre>
 * package com.example.entity.generated;
 *
 * &#64;Repository
 * public interface ProductRepository extends JpaRepository&lt;Product, Long&gt; {}
 * </pre>
 *
 * <p>The generated interface is placed in the same {@code .generated} subpackage
 * as the controller and security configurer, so it is picked up automatically
 * by Spring Data's repository scanning.
 */
public class RepositoryGenerator {

    private final ProcessingEnvironment processingEnv;

    public RepositoryGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    public void generate(EntityModel model) {
        ClassName entityClass   = ClassName.bestGuess(model.entityClassName());
        ClassName idClass       = ClassName.bestGuess(model.idClassName());
        ClassName jpaRepository = ClassName.get("org.springframework.data.jpa.repository", "JpaRepository");
        ClassName repository    = ClassName.get("org.springframework.stereotype", "Repository");

        TypeName superInterface = ParameterizedTypeName.get(jpaRepository, entityClass, idClass);

        TypeSpec repoInterface = TypeSpec.interfaceBuilder(model.entitySimpleName() + "Repository")
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Generated by spring-xpose — do not edit.\n"
                + "Spring Data JPA repository for {@link $T}.\n", entityClass)
            .addAnnotation(repository)
            .addSuperinterface(superInterface)
            .build();

        try {
            JavaFile.builder(model.packageName() + ".generated", repoInterface)
                .addFileComment("Generated by spring-xpose — do not edit")
                .build()
                .writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw new RuntimeException(
                "Failed to write repository for " + model.entitySimpleName(), e);
        }
    }
}

