package io.github.notablogger.springxpose.processor.generator;

import com.squareup.javapoet.*;
import io.github.notablogger.springxpose.processor.model.EntityModel;
import io.github.notablogger.springxpose.processor.model.FieldModel;
import io.github.notablogger.springxpose.processor.model.RelationFieldModel;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates a {@code <Entity>RequestDto} class for write operations (CREATE / UPDATE).
 *
 * <p>Rules:
 * <ul>
 *   <li>The {@code id} field is excluded — the ID comes from the path variable, not the body.</li>
 *   <li>Fields in {@code ignoredFields} are excluded.</li>
 *   <li>Jakarta Validation annotations on the entity field are re-applied to the request DTO field.</li>
 *   <li>SINGLE relations (ManyToOne / OneToOne) are always represented as {@code Long <field>Id}
 *       so clients send plain IDs, keeping the API simple and decoupled from the entity graph.</li>
 *   <li>COLLECTION relations are excluded (same as the response DTO).</li>
 * </ul>
 */
public class RequestDtoGenerator {

    private final ProcessingEnvironment processingEnv;

    public RequestDtoGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    public void generate(EntityModel model) {
        String requestDtoName = model.entitySimpleName() + "RequestDto";
        TypeSpec.Builder dto = TypeSpec.classBuilder(requestDtoName)
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc(
                "Generated request DTO for {@link $L} write operations — do not edit.\n"
                    + "<p>Use this class as the {@code @RequestBody} for CREATE and UPDATE endpoints.\n"
                    + "Relation fields are expressed as {@code Long <field>Id}.\n",
                model.entitySimpleName());

        // Scalar fields — skip id, @Version, and ignoredFields; carry validation annotations
        for (FieldModel field : model.fields()) {
            if (field.isId()) continue; // id comes from path, not body
            if (model.hasVersion() && field.name().equals(model.versionFieldName())) continue; // skip @Version field
            if (model.ignoredFields().contains(field.name())) continue;

            TypeName typeName = resolveTypeName(field.typeName());
            FieldSpec.Builder fieldBuilder = FieldSpec.builder(typeName, field.name(), Modifier.PRIVATE);

            // Re-apply jakarta.validation annotations from the entity field
            for (AnnotationMirror am : field.validationAnnotations()) {
                fieldBuilder.addAnnotation(AnnotationSpec.get(am));
            }

            dto.addField(fieldBuilder.build());
            dto.addMethod(getter(field.name(), typeName));
            dto.addMethod(setter(field.name(), typeName));
        }

        // Relation fields — SINGLE only, always as Long <field>Id
        for (RelationFieldModel rel : model.relations()) {
            if ("COLLECTION".equals(rel.relationType())) continue;
            if (model.ignoredFields().contains(rel.name())) continue;

            String idFieldName = rel.name() + "Id";
            dto.addField(TypeName.LONG.box(), idFieldName, Modifier.PRIVATE);
            dto.addMethod(getter(idFieldName, TypeName.LONG.box()));
            dto.addMethod(setter(idFieldName, TypeName.LONG.box()));
        }

        try {
            JavaFile.builder(model.packageName() + ".generated", dto.build())
                .addFileComment("Generated by spring-xpose — do not edit")
                .build()
                .writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw new RuntimeException("Failed to write RequestDto for " + model.entitySimpleName(), e);
        }
    }

    private static TypeName resolveTypeName(String rawTypeName) {
        String typeName = rawTypeName.replaceAll("@\\S+\\s*", "").trim();
        return switch (typeName) {
            case "long", "java.lang.Long"      -> TypeName.LONG.box();
            case "int", "java.lang.Integer"    -> TypeName.INT.box();
            case "double", "java.lang.Double"  -> TypeName.DOUBLE.box();
            case "boolean", "java.lang.Boolean"-> TypeName.BOOLEAN.box();
            case "float", "java.lang.Float"    -> TypeName.FLOAT.box();
            default -> ClassName.bestGuess(typeName);
        };
    }

    private static MethodSpec getter(String name, TypeName type) {
        String prefix = type.equals(TypeName.BOOLEAN.box()) ? "is" : "get";
        return MethodSpec.methodBuilder(prefix + capitalize(name))
            .addModifiers(Modifier.PUBLIC)
            .returns(type)
            .addStatement("return this.$L", name)
            .build();
    }

    private static MethodSpec setter(String name, TypeName type) {
        return MethodSpec.methodBuilder("set" + capitalize(name))
            .addModifiers(Modifier.PUBLIC)
            .addParameter(type, name)
            .addStatement("this.$L = $L", name, name)
            .build();
    }

    private static String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}
