package io.github.notablogger.springxpose.processor.generator;

import com.squareup.javapoet.*;
import io.github.notablogger.springxpose.annotation.AuthType;
import io.github.notablogger.springxpose.annotation.Operation;
import io.github.notablogger.springxpose.processor.model.EntityModel;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import java.io.IOException;

public class SecurityConfigurerGenerator {

    private final ProcessingEnvironment processingEnv;

    public SecurityConfigurerGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    public void generate(EntityModel model) {
        ClassName httpSecurity  = ClassName.get("org.springframework.security.config.annotation.web.builders", "HttpSecurity");
        ClassName filterChain   = ClassName.get("org.springframework.security.web", "SecurityFilterChain");
        ClassName customizer    = ClassName.get("org.springframework.security.config", "Customizer");
        ClassName httpMethod    = ClassName.get("org.springframework.http", "HttpMethod");
        ClassName order         = ClassName.get("org.springframework.core.annotation", "Order");
        ClassName bean          = ClassName.get("org.springframework.context.annotation", "Bean");
        ClassName configuration = ClassName.get("org.springframework.context.annotation", "Configuration");

        String entity    = model.entitySimpleName();
        String basePath  = "/api/" + model.basePath();
        String beanName  = Character.toLowerCase(entity.charAt(0)) + entity.substring(1) + "SecurityFilterChain";
        int orderValue   = 100 + Math.abs(Math.abs(entity.hashCode()) % 900);

        MethodSpec.Builder method = MethodSpec.methodBuilder(beanName)
            .addAnnotation(bean)
            .addAnnotation(AnnotationSpec.builder(order).addMember("value", "$L", orderValue).build())
            .addModifiers(Modifier.PUBLIC)
            .returns(filterChain)
            .addParameter(httpSecurity, "http")
            .addException(Exception.class);

        // securityMatcher
        method.addStatement("http.securityMatcher($S, $S)", basePath, basePath + "/**");

        // disable CSRF — REST APIs don't use cookie-based sessions
        method.addStatement("http.csrf(csrf -> csrf.disable())");

        // authorizeHttpRequests
        buildAuthStatements(method, model, basePath, httpMethod);

        // auth mechanism
        switch (model.authType()) {
            case BASIC  -> method.addStatement("http.httpBasic($T.withDefaults())", customizer);
            case OAUTH2 -> method.addStatement(
                "http.oauth2ResourceServer(oauth2 -> oauth2.jwt($T.withDefaults()))", customizer);
            case NONE   -> { /* no auth mechanism */ }
        }

        method.addStatement("return http.build()");

        TypeSpec configurer = TypeSpec.classBuilder(entity + "SecurityConfigurer")
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Generated by spring-xpose — do not edit\n")
            .addAnnotation(configuration)
            .addMethod(method.build())
            .build();

        try {
            JavaFile.builder(model.packageName() + ".generated", configurer)
                .addFileComment("Generated by spring-xpose — do not edit")
                .build()
                .writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw new RuntimeException("Failed to write security configurer for " + entity, e);
        }
    }

    private void buildAuthStatements(MethodSpec.Builder method, EntityModel model,
                                     String basePath, ClassName httpMethod) {
        boolean exposeFindAll  = model.operations().contains(Operation.FIND_ALL);
        boolean exposeFindById = model.operations().contains(Operation.FIND_BY_ID);
        boolean exposeCreate   = model.operations().contains(Operation.CREATE);
        boolean exposeUpdate   = model.operations().contains(Operation.UPDATE);
        boolean exposeDelete   = model.operations().contains(Operation.DELETE);

        if (model.authType() == AuthType.NONE) {
            CodeBlock.Builder auth = CodeBlock.builder();
            auth.add("http.authorizeHttpRequests(auth -> auth\n");
            if (exposeFindAll) {
                auth.add("    .requestMatchers($T.GET, $S).permitAll()\n", httpMethod, basePath);
            }
            if (exposeFindById) {
                auth.add("    .requestMatchers($T.GET, $S).permitAll()\n", httpMethod, basePath + "/**");
            }
            if (exposeCreate) {
                auth.add("    .requestMatchers($T.POST, $S).permitAll()\n", httpMethod, basePath);
            }
            if (exposeUpdate) {
                auth.add("    .requestMatchers($T.PUT, $S).permitAll()\n", httpMethod, basePath + "/**");
            }
            if (exposeDelete) {
                auth.add("    .requestMatchers($T.DELETE, $S).permitAll()\n", httpMethod, basePath + "/**");
            }
            auth.add("    .anyRequest().denyAll());\n");
            method.addCode(auth.build());
            return;
        }

        boolean hasReadRoles  = !model.readRoles().isEmpty();
        boolean hasWriteRoles = !model.writeRoles().isEmpty();
        boolean hasRoles      = !model.roles().isEmpty();

        String readRoles  = hasReadRoles  ? formatRoles(model.readRoles().toArray(new String[0]))
                          : hasRoles      ? formatRoles(model.roles().toArray(new String[0]))
                          : null;
        String writeRoles = hasWriteRoles ? formatRoles(model.writeRoles().toArray(new String[0]))
                          : hasRoles      ? formatRoles(model.roles().toArray(new String[0]))
                          : null;

        CodeBlock.Builder auth = CodeBlock.builder();
        auth.add("http.authorizeHttpRequests(auth -> auth\n");

        if (exposeFindAll) {
            if (readRoles != null) {
                auth.add("    .requestMatchers($T.GET, $S).hasAnyRole($L)\n", httpMethod, basePath, readRoles);
            } else {
                auth.add("    .requestMatchers($T.GET, $S).authenticated()\n", httpMethod, basePath);
            }
        }
        if (exposeFindById) {
            if (readRoles != null) {
                auth.add("    .requestMatchers($T.GET, $S).hasAnyRole($L)\n", httpMethod, basePath + "/**", readRoles);
            } else {
                auth.add("    .requestMatchers($T.GET, $S).authenticated()\n", httpMethod, basePath + "/**");
            }
        }

        if (exposeCreate) {
            if (writeRoles != null) {
                auth.add("    .requestMatchers($T.POST, $S).hasAnyRole($L)\n", httpMethod, basePath, writeRoles);
            } else {
                auth.add("    .requestMatchers($T.POST, $S).authenticated()\n", httpMethod, basePath);
            }
        }
        if (exposeUpdate) {
            if (writeRoles != null) {
                auth.add("    .requestMatchers($T.PUT, $S).hasAnyRole($L)\n", httpMethod, basePath + "/**", writeRoles);
            } else {
                auth.add("    .requestMatchers($T.PUT, $S).authenticated()\n", httpMethod, basePath + "/**");
            }
        }
        if (exposeDelete) {
            if (writeRoles != null) {
                auth.add("    .requestMatchers($T.DELETE, $S).hasAnyRole($L)\n", httpMethod, basePath + "/**", writeRoles);
            } else {
                auth.add("    .requestMatchers($T.DELETE, $S).authenticated()\n", httpMethod, basePath + "/**");
            }
        }

        auth.add("    .anyRequest().denyAll());\n");
        method.addCode(auth.build());
    }

    private static String formatRoles(String[] roles) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < roles.length; i++) {
            String role = roles[i].startsWith("ROLE_") ? roles[i].substring(5) : roles[i];
            if (i > 0) sb.append(", ");
            sb.append("\"").append(role).append("\"");
        }
        return sb.toString();
    }
}
