package io.github.notablogger.springxpose.processor.generator;

import com.squareup.javapoet.*;
import io.github.notablogger.springxpose.annotation.StoreType;
import io.github.notablogger.springxpose.processor.model.EntityModel;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates a {@code <Entity>Spec} class that builds a filter query from a
 * {@code <Entity>FilterParams} object.
 *
 * <ul>
 *   <li><b>JPA</b> — returns a {@code Specification<Entity>} (lambda over {@code CriteriaBuilder}).
 *       Each non-null filter param adds a {@code cb.equal} predicate. The repository must
 *       also extend {@code JpaSpecificationExecutor} (handled by {@link RepositoryGenerator}).</li>
 *   <li><b>MongoDB</b> — returns a Spring Data {@code Query} built from {@code Criteria}.
 *       Each non-null filter param adds a {@code Criteria.where(field).is(value)} condition.
 *       The generated controller uses {@code MongoTemplate} to execute the query.</li>
 * </ul>
 *
 * <p>Example JPA output for {@code filterableFields = {"name", "status"}}:
 * <pre>
 * public class ProductSpec {
 *     public static Specification&lt;Product&gt; withFilters(ProductFilterParams f) {
 *         return (root, query, cb) -> {
 *             List&lt;Predicate&gt; predicates = new ArrayList&lt;&gt;();
 *             if (f.getName() != null)
 *                 predicates.add(cb.equal(root.get("name"), f.getName()));
 *             if (f.getStatus() != null)
 *                 predicates.add(cb.equal(root.get("status"), f.getStatus()));
 *             return cb.and(predicates.toArray(new Predicate[0]));
 *         };
 *     }
 * }
 * </pre>
 *
 * <p>Example MongoDB output for {@code filterableFields = {"author"}}:
 * <pre>
 * public class NoteSpec {
 *     public static Query withFilters(NoteFilterParams f) {
 *         List&lt;Criteria&gt; conditions = new ArrayList&lt;&gt;();
 *         if (f.getAuthor() != null)
 *             conditions.add(Criteria.where("author").is(f.getAuthor()));
 *         if (conditions.isEmpty())
 *             return new Query();
 *         return Query.query(new Criteria().andOperator(conditions));
 *     }
 * }
 * </pre>
 */
public class SpecificationGenerator {

    private final ProcessingEnvironment processingEnv;

    public SpecificationGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    public void generate(EntityModel model) {
        if (!model.hasFilterableFields()) return;

        if (model.storeType() == StoreType.JPA) {
            generateJpaSpec(model);
        } else {
            generateMongoSpec(model);
        }
    }

    // ── JPA ─────────────────────────────────────────────────────────────────

    private void generateJpaSpec(EntityModel model) {
        ClassName entityClass     = ClassName.bestGuess(model.entityClassName());
        ClassName filterParamsCls = ClassName.get(model.packageName() + ".generated",
            model.entitySimpleName() + "FilterParams");
        ClassName specification   = ClassName.get("org.springframework.data.jpa.domain", "Specification");
        ClassName predicate       = ClassName.get("jakarta.persistence.criteria", "Predicate");
        ClassName arrayList       = ClassName.get("java.util", "ArrayList");
        ClassName list            = ClassName.get("java.util", "List");
        TypeName  specType        = ParameterizedTypeName.get(specification, entityClass);
        TypeName  predicateList   = ParameterizedTypeName.get(list, predicate);

        // Build the lambda body as raw code so the indented multi-statement lambda compiles cleanly.
        MethodSpec.Builder withFilters = MethodSpec.methodBuilder("withFilters")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .returns(specType)
            .addParameter(filterParamsCls, "f")
            .addCode("return (root, query, cb) -> {\n")
            .addCode("    $T<$T> predicates = new $T<>();\n", list, predicate, arrayList);

        for (String fieldName : model.filterableFields()) {
            String getter = "get" + capitalize(fieldName);
            withFilters
                .addCode("    if (f.$L() != null)\n", getter)
                .addCode("        predicates.add(cb.equal(root.get($S), f.$L()));\n", fieldName, getter);
        }

        withFilters
            .addCode("    return cb.and(predicates.toArray(new $T[0]));\n", predicate)
            .addCode("};\n");

        TypeSpec spec = TypeSpec.classBuilder(model.entitySimpleName() + "Spec")
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Generated by spring-xpose — do not edit.\n"
                + "JPA {@link $T} builder for exact-match filtering on "
                + "{@code GET /api/" + model.basePath() + "}.\n", specification)
            .addMethod(withFilters.build())
            .build();

        write(model, spec);
    }

    // ── MongoDB ──────────────────────────────────────────────────────────────

    private void generateMongoSpec(EntityModel model) {
        ClassName filterParamsCls = ClassName.get(model.packageName() + ".generated",
            model.entitySimpleName() + "FilterParams");
        ClassName queryClass      = ClassName.get("org.springframework.data.mongodb.core.query", "Query");
        ClassName criteriaClass   = ClassName.get("org.springframework.data.mongodb.core.query", "Criteria");
        ClassName arrayList       = ClassName.get("java.util", "ArrayList");
        ClassName list            = ClassName.get("java.util", "List");
        TypeName  criteriaList    = ParameterizedTypeName.get(list, criteriaClass);

        MethodSpec.Builder withFilters = MethodSpec.methodBuilder("withFilters")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .returns(queryClass)
            .addParameter(filterParamsCls, "f")
            .addStatement("$T<$T> conditions = new $T<>()", list, criteriaClass, arrayList);

        for (String fieldName : model.filterableFields()) {
            String getter = "get" + capitalize(fieldName);
            withFilters
                .beginControlFlow("if (f.$L() != null)", getter)
                .addStatement("conditions.add($T.where($S).is(f.$L()))", criteriaClass, fieldName, getter)
                .endControlFlow();
        }

        withFilters
            .beginControlFlow("if (conditions.isEmpty())")
            .addStatement("return new $T()", queryClass)
            .endControlFlow()
            .addStatement("return $T.query(new $T().andOperator(conditions))", queryClass, criteriaClass);

        TypeSpec spec = TypeSpec.classBuilder(model.entitySimpleName() + "Spec")
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Generated by spring-xpose — do not edit.\n"
                + "MongoDB {@link $T} builder for exact-match filtering on "
                + "{@code GET /api/" + model.basePath() + "}.\n", queryClass)
            .addMethod(withFilters.build())
            .build();

        write(model, spec);
    }

    // ── helpers ──────────────────────────────────────────────────────────────

    private void write(EntityModel model, TypeSpec spec) {
        try {
            JavaFile.builder(model.packageName() + ".generated", spec)
                .addFileComment("Generated by spring-xpose — do not edit")
                .build()
                .writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw new RuntimeException("Failed to write Spec for " + model.entitySimpleName(), e);
        }
    }

    private static String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}
