package io.github.springxpose.processor.generator;

import com.squareup.javapoet.*;
import io.github.springxpose.annotation.Operation;
import io.github.springxpose.processor.model.EntityModel;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.List;

public class RestControllerGenerator {

    // OpenAPI annotation class names (springdoc / swagger-core 2.x)
    private static final ClassName OA_TAG          = ClassName.get("io.swagger.v3.oas.annotations", "tags", "Tag");
    private static final ClassName OA_OPERATION    = ClassName.get("io.swagger.v3.oas.annotations", "Operation");
    private static final ClassName OA_API_RESPONSE = ClassName.get("io.swagger.v3.oas.annotations.responses", "ApiResponse");
    private static final ClassName OA_API_RESPONSES= ClassName.get("io.swagger.v3.oas.annotations.responses", "ApiResponses");
    private static final ClassName OA_PARAMETER    = ClassName.get("io.swagger.v3.oas.annotations", "Parameter");
    private static final ClassName OA_REQUEST_BODY = ClassName.get("io.swagger.v3.oas.annotations.parameters", "RequestBody");
    private static final ClassName OA_CONTENT      = ClassName.get("io.swagger.v3.oas.annotations.media", "Content");
    private static final ClassName OA_SCHEMA       = ClassName.get("io.swagger.v3.oas.annotations.media", "Schema");

    private final ProcessingEnvironment processingEnv;

    public RestControllerGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    public void generate(EntityModel model) {
        ClassName entityClass        = ClassName.bestGuess(model.entityClassName());
        ClassName repositoryClass    = ClassName.get(model.packageName() + ".generated", model.entitySimpleName() + "Repository");
        ClassName idClass            = ClassName.bestGuess(model.idClassName());
        ClassName responseEntity     = ClassName.get("org.springframework.http", "ResponseEntity");
        ClassName listClass          = ClassName.get("java.util", "List");
        ClassName httpStatus         = ClassName.get("org.springframework.http", "HttpStatus");
        ClassName serializationContext = ClassName.get("io.github.springxpose.serializer", "SerializationContext");

        String entity    = model.entitySimpleName();
        String entityLc  = entity.toLowerCase();

        TypeSpec.Builder controller = TypeSpec.classBuilder(entity + "Controller")
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Generated by spring-xpose — do not edit\n")
            .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "RestController"))
            .addAnnotation(AnnotationSpec.builder(ClassName.get("org.springframework.web.bind.annotation", "RequestMapping"))
                .addMember("value", "$S", "/api/" + model.basePath())
                .build())
            // @Tag(name = "Product", description = "CRUD operations for Product")
            .addAnnotation(AnnotationSpec.builder(OA_TAG)
                .addMember("name", "$S", entity)
                .addMember("description", "$S", "CRUD operations for " + entity)
                .build())
            .addField(FieldSpec.builder(repositoryClass, "repository", Modifier.PRIVATE, Modifier.FINAL).build())
            .addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(repositoryClass, "repository")
                .addStatement("this.repository = repository")
                .build());

        if (model.operations().contains(Operation.FIND_ALL)) {
            TypeName returnType = ParameterizedTypeName.get(responseEntity,
                ParameterizedTypeName.get(listClass, entityClass));
            controller.addMethod(MethodSpec.methodBuilder("findAll")
                .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "GetMapping"))
                .addAnnotation(AnnotationSpec.builder(OA_OPERATION)
                    .addMember("summary", "$S", "List all " + entity + " records")
                    .addMember("operationId", "$S", "findAll" + entity)
                    .build())
                .addAnnotation(AnnotationSpec.builder(OA_API_RESPONSES)
                    .addMember("value", "{\n  @$T(responseCode = $S, description = $S)\n}", OA_API_RESPONSE, "200", "Successful retrieval")
                    .build())
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType)
                .addStatement("$T.set($T.Mode.LIST)", serializationContext, serializationContext)
                .beginControlFlow("try")
                .addStatement("return $T.ok(repository.findAll())", responseEntity)
                .nextControlFlow("finally")
                .addStatement("$T.clear()", serializationContext)
                .endControlFlow()
                .build());
        }

        if (model.operations().contains(Operation.FIND_BY_ID)) {
            TypeName returnType = ParameterizedTypeName.get(responseEntity, entityClass);
            controller.addMethod(MethodSpec.methodBuilder("findById")
                .addAnnotation(AnnotationSpec.builder(ClassName.get("org.springframework.web.bind.annotation", "GetMapping"))
                    .addMember("value", "$S", "/{id}")
                    .build())
                .addAnnotation(AnnotationSpec.builder(OA_OPERATION)
                    .addMember("summary", "$S", "Get a " + entity + " by ID")
                    .addMember("operationId", "$S", "find" + entity + "ById")
                    .build())
                .addAnnotation(AnnotationSpec.builder(OA_API_RESPONSES)
                    .addMember("value", "{\n  @$T(responseCode = $S, description = $S),\n  @$T(responseCode = $S, description = $S)\n}",
                        OA_API_RESPONSE, "200", "Found",
                        OA_API_RESPONSE, "404", "Not found")
                    .build())
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType)
                .addParameter(ParameterSpec.builder(idClass, "id")
                    .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "PathVariable"))
                    .addAnnotation(AnnotationSpec.builder(OA_PARAMETER)
                        .addMember("description", "$S", "ID of the " + entity + " to retrieve")
                        .addMember("required", "$L", true)
                        .build())
                    .build())
                .addStatement("$T.set($T.Mode.SINGLE)", serializationContext, serializationContext)
                .beginControlFlow("try")
                .addStatement("return repository.findById(id)\n    .map($T::ok)\n    .orElse($T.notFound().build())", responseEntity, responseEntity)
                .nextControlFlow("finally")
                .addStatement("$T.clear()", serializationContext)
                .endControlFlow()
                .build());
        }

        if (model.operations().contains(Operation.CREATE)) {
            TypeName returnType = ParameterizedTypeName.get(responseEntity, entityClass);
            controller.addMethod(MethodSpec.methodBuilder("create")
                .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "PostMapping"))
                .addAnnotation(AnnotationSpec.builder(OA_OPERATION)
                    .addMember("summary", "$S", "Create a new " + entity)
                    .addMember("operationId", "$S", "create" + entity)
                    .build())
                .addAnnotation(AnnotationSpec.builder(OA_API_RESPONSES)
                    .addMember("value", "{\n  @$T(responseCode = $S, description = $S),\n  @$T(responseCode = $S, description = $S)\n}",
                        OA_API_RESPONSE, "201", "Created",
                        OA_API_RESPONSE, "400", "Validation error")
                    .build())
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType)
                .addParameter(ParameterSpec.builder(entityClass, "entity")
                    .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "RequestBody"))
                    .addAnnotation(ClassName.get("jakarta.validation", "Valid"))
                    .addAnnotation(AnnotationSpec.builder(OA_REQUEST_BODY)
                        .addMember("description", "$S", entity + " to create")
                        .addMember("required", "$L", true)
                        .build())
                    .build())
                .addStatement("return $T.status($T.CREATED).body(repository.save(entity))", responseEntity, httpStatus)
                .build());
        }

        if (model.operations().contains(Operation.UPDATE)) {
            TypeName returnType = ParameterizedTypeName.get(responseEntity, entityClass);
            String setIdStatement = "entity.set" + capitalize(model.idFieldName()) + "(id)";
            controller.addMethod(MethodSpec.methodBuilder("update")
                .addAnnotation(AnnotationSpec.builder(ClassName.get("org.springframework.web.bind.annotation", "PutMapping"))
                    .addMember("value", "$S", "/{id}")
                    .build())
                .addAnnotation(AnnotationSpec.builder(OA_OPERATION)
                    .addMember("summary", "$S", "Update an existing " + entity)
                    .addMember("operationId", "$S", "update" + entity)
                    .build())
                .addAnnotation(AnnotationSpec.builder(OA_API_RESPONSES)
                    .addMember("value", "{\n  @$T(responseCode = $S, description = $S),\n  @$T(responseCode = $S, description = $S),\n  @$T(responseCode = $S, description = $S)\n}",
                        OA_API_RESPONSE, "200", "Updated",
                        OA_API_RESPONSE, "400", "Validation error",
                        OA_API_RESPONSE, "404", "Not found")
                    .build())
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType)
                .addParameter(ParameterSpec.builder(idClass, "id")
                    .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "PathVariable"))
                    .addAnnotation(AnnotationSpec.builder(OA_PARAMETER)
                        .addMember("description", "$S", "ID of the " + entity + " to update")
                        .addMember("required", "$L", true)
                        .build())
                    .build())
                .addParameter(ParameterSpec.builder(entityClass, "entity")
                    .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "RequestBody"))
                    .addAnnotation(ClassName.get("jakarta.validation", "Valid"))
                    .addAnnotation(AnnotationSpec.builder(OA_REQUEST_BODY)
                        .addMember("description", "$S", "Updated " + entity + " data")
                        .addMember("required", "$L", true)
                        .build())
                    .build())
                .beginControlFlow("if (!repository.existsById(id))")
                .addStatement("return $T.notFound().build()", responseEntity)
                .endControlFlow()
                .addStatement(setIdStatement)
                .addStatement("return $T.ok(repository.save(entity))", responseEntity)
                .build());
        }

        if (model.operations().contains(Operation.DELETE)) {
            TypeName returnType = ParameterizedTypeName.get(responseEntity, ClassName.get(Void.class));
            controller.addMethod(MethodSpec.methodBuilder("delete")
                .addAnnotation(AnnotationSpec.builder(ClassName.get("org.springframework.web.bind.annotation", "DeleteMapping"))
                    .addMember("value", "$S", "/{id}")
                    .build())
                .addAnnotation(AnnotationSpec.builder(OA_OPERATION)
                    .addMember("summary", "$S", "Delete a " + entity + " by ID")
                    .addMember("operationId", "$S", "delete" + entity)
                    .build())
                .addAnnotation(AnnotationSpec.builder(OA_API_RESPONSES)
                    .addMember("value", "{\n  @$T(responseCode = $S, description = $S),\n  @$T(responseCode = $S, description = $S)\n}",
                        OA_API_RESPONSE, "204", "Deleted",
                        OA_API_RESPONSE, "404", "Not found")
                    .build())
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType)
                .addParameter(ParameterSpec.builder(idClass, "id")
                    .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "PathVariable"))
                    .addAnnotation(AnnotationSpec.builder(OA_PARAMETER)
                        .addMember("description", "$S", "ID of the " + entity + " to delete")
                        .addMember("required", "$L", true)
                        .build())
                    .build())
                .beginControlFlow("if (!repository.existsById(id))")
                .addStatement("return $T.notFound().build()", responseEntity)
                .endControlFlow()
                .addStatement("repository.deleteById(id)")
                .addStatement("return $T.noContent().build()", responseEntity)
                .build());
        }

        try {
            JavaFile.builder(model.packageName() + ".generated", controller.build())
                .addFileComment("Generated by spring-xpose — do not edit")
                .build()
                .writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw new RuntimeException("Failed to write controller for " + model.entitySimpleName(), e);
        }
    }

    private static String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}
