package io.github.springxpose.processor.generator;

import com.squareup.javapoet.*;
import io.github.springxpose.annotation.Operation;
import io.github.springxpose.processor.model.EntityModel;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.List;

public class RestControllerGenerator {

    private final ProcessingEnvironment processingEnv;

    public RestControllerGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    public void generate(EntityModel model) {
        ClassName entityClass = ClassName.bestGuess(model.entityClassName());
        // Reference the generated repository in the .generated subpackage
        ClassName repositoryClass = ClassName.get(model.packageName() + ".generated", model.entitySimpleName() + "Repository");
        ClassName idClass = ClassName.bestGuess(model.idClassName());
        ClassName responseEntity = ClassName.get("org.springframework.http", "ResponseEntity");
        ClassName listClass = ClassName.get("java.util", "List");
        ClassName httpStatus = ClassName.get("org.springframework.http", "HttpStatus");
        ClassName serializationContext = ClassName.get("io.github.springxpose.serializer", "SerializationContext");

        TypeSpec.Builder controller = TypeSpec.classBuilder(model.entitySimpleName() + "Controller")
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Generated by spring-xpose — do not edit\n")
            .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "RestController"))
            .addAnnotation(AnnotationSpec.builder(ClassName.get("org.springframework.web.bind.annotation", "RequestMapping"))
                .addMember("value", "$S", "/api/" + model.basePath())
                .build())
            .addField(FieldSpec.builder(repositoryClass, "repository", Modifier.PRIVATE, Modifier.FINAL).build())
            .addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(repositoryClass, "repository")
                .addStatement("this.repository = repository")
                .build());

        if (model.operations().contains(Operation.FIND_ALL)) {
            TypeName returnType = ParameterizedTypeName.get(responseEntity,
                ParameterizedTypeName.get(listClass, entityClass));
            controller.addMethod(MethodSpec.methodBuilder("findAll")
                .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "GetMapping"))
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType)
                .addStatement("$T.set($T.Mode.LIST)", serializationContext, serializationContext)
                .beginControlFlow("try")
                .addStatement("return $T.ok(repository.findAll())", responseEntity)
                .nextControlFlow("finally")
                .addStatement("$T.clear()", serializationContext)
                .endControlFlow()
                .build());
        }

        if (model.operations().contains(Operation.FIND_BY_ID)) {
            TypeName returnType = ParameterizedTypeName.get(responseEntity, entityClass);
            controller.addMethod(MethodSpec.methodBuilder("findById")
                .addAnnotation(AnnotationSpec.builder(ClassName.get("org.springframework.web.bind.annotation", "GetMapping"))
                    .addMember("value", "$S", "/{id}")
                    .build())
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType)
                .addParameter(ParameterSpec.builder(idClass, "id")
                    .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "PathVariable"))
                    .build())
                .addStatement("$T.set($T.Mode.SINGLE)", serializationContext, serializationContext)
                .beginControlFlow("try")
                .addStatement("return repository.findById(id)\n    .map($T::ok)\n    .orElse($T.notFound().build())", responseEntity, responseEntity)
                .nextControlFlow("finally")
                .addStatement("$T.clear()", serializationContext)
                .endControlFlow()
                .build());
        }

        if (model.operations().contains(Operation.CREATE)) {
            TypeName returnType = ParameterizedTypeName.get(responseEntity, entityClass);
            controller.addMethod(MethodSpec.methodBuilder("create")
                .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "PostMapping"))
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType)
                .addParameter(ParameterSpec.builder(entityClass, "entity")
                    .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "RequestBody"))
                    .addAnnotation(ClassName.get("jakarta.validation", "Valid"))
                    .build())
                .addStatement("return $T.status($T.CREATED).body(repository.save(entity))", responseEntity, httpStatus)
                .build());
        }

        if (model.operations().contains(Operation.UPDATE)) {
            TypeName returnType = ParameterizedTypeName.get(responseEntity, entityClass);
            String setIdStatement = "entity.set" + capitalize(model.idFieldName()) + "(id)";
            controller.addMethod(MethodSpec.methodBuilder("update")
                .addAnnotation(AnnotationSpec.builder(ClassName.get("org.springframework.web.bind.annotation", "PutMapping"))
                    .addMember("value", "$S", "/{id}")
                    .build())
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType)
                .addParameter(ParameterSpec.builder(idClass, "id")
                    .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "PathVariable"))
                    .build())
                .addParameter(ParameterSpec.builder(entityClass, "entity")
                    .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "RequestBody"))
                    .addAnnotation(ClassName.get("jakarta.validation", "Valid"))
                    .build())
                .beginControlFlow("if (!repository.existsById(id))")
                .addStatement("return $T.notFound().build()", responseEntity)
                .endControlFlow()
                .addStatement(setIdStatement)
                .addStatement("return $T.ok(repository.save(entity))", responseEntity)
                .build());
        }

        if (model.operations().contains(Operation.DELETE)) {
            TypeName returnType = ParameterizedTypeName.get(responseEntity, ClassName.get(Void.class));
            controller.addMethod(MethodSpec.methodBuilder("delete")
                .addAnnotation(AnnotationSpec.builder(ClassName.get("org.springframework.web.bind.annotation", "DeleteMapping"))
                    .addMember("value", "$S", "/{id}")
                    .build())
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType)
                .addParameter(ParameterSpec.builder(idClass, "id")
                    .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "PathVariable"))
                    .build())
                .beginControlFlow("if (!repository.existsById(id))")
                .addStatement("return $T.notFound().build()", responseEntity)
                .endControlFlow()
                .addStatement("repository.deleteById(id)")
                .addStatement("return $T.noContent().build()", responseEntity)
                .build());
        }

        try {
            JavaFile.builder(model.packageName() + ".generated", controller.build())
                .addFileComment("Generated by spring-xpose — do not edit")
                .build()
                .writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw new RuntimeException("Failed to write controller for " + model.entitySimpleName(), e);
        }
    }

    private static String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}
