package io.github.springxpose.processor.generator;

import com.squareup.javapoet.*;
import io.github.springxpose.annotation.AuthType;
import io.github.springxpose.processor.model.EntityModel;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import java.io.IOException;

public class SecurityConfigurerGenerator {

    private final ProcessingEnvironment processingEnv;

    public SecurityConfigurerGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    public void generate(EntityModel model) {
        ClassName httpSecurity  = ClassName.get("org.springframework.security.config.annotation.web.builders", "HttpSecurity");
        ClassName filterChain   = ClassName.get("org.springframework.security.web", "SecurityFilterChain");
        ClassName customizer    = ClassName.get("org.springframework.security.config", "Customizer");
        ClassName httpMethod    = ClassName.get("org.springframework.http", "HttpMethod");
        ClassName order         = ClassName.get("org.springframework.core.annotation", "Order");
        ClassName bean          = ClassName.get("org.springframework.context.annotation", "Bean");
        ClassName configuration = ClassName.get("org.springframework.context.annotation", "Configuration");

        String entity    = model.entitySimpleName();
        String basePath  = "/api/" + model.basePath();
        String beanName  = Character.toLowerCase(entity.charAt(0)) + entity.substring(1) + "SecurityFilterChain";
        int orderValue   = 100 + Math.abs(Math.abs(entity.hashCode()) % 900);

        MethodSpec.Builder method = MethodSpec.methodBuilder(beanName)
            .addAnnotation(bean)
            .addAnnotation(AnnotationSpec.builder(order).addMember("value", "$L", orderValue).build())
            .addModifiers(Modifier.PUBLIC)
            .returns(filterChain)
            .addParameter(httpSecurity, "http")
            .addException(Exception.class);

        // securityMatcher
        method.addStatement("http.securityMatcher($S, $S)", basePath, basePath + "/**");

        // authorizeHttpRequests
        buildAuthStatements(method, model, basePath, httpMethod);

        // auth mechanism
        switch (model.authType()) {
            case BASIC  -> method.addStatement("http.httpBasic($T.withDefaults())", customizer);
            case OAUTH2 -> method.addStatement(
                "http.oauth2ResourceServer(oauth2 -> oauth2.jwt($T.withDefaults()))", customizer);
            case NONE   -> { /* no auth mechanism */ }
        }

        method.addStatement("return http.build()");

        TypeSpec configurer = TypeSpec.classBuilder(entity + "SecurityConfigurer")
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Generated by spring-xpose — do not edit\n")
            .addAnnotation(configuration)
            .addMethod(method.build())
            .build();

        try {
            JavaFile.builder(model.packageName() + ".generated", configurer)
                .addFileComment("Generated by spring-xpose — do not edit")
                .build()
                .writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw new RuntimeException("Failed to write security configurer for " + entity, e);
        }
    }

    private void buildAuthStatements(MethodSpec.Builder method, EntityModel model,
                                     String basePath, ClassName httpMethod) {
        if (model.authType() == AuthType.NONE) {
            method.addStatement(
                "http.authorizeHttpRequests(auth -> auth.anyRequest().permitAll())");
            return;
        }

        boolean hasReadRoles  = !model.readRoles().isEmpty();
        boolean hasWriteRoles = !model.writeRoles().isEmpty();
        boolean hasRoles      = !model.roles().isEmpty();

        String readRoles  = hasReadRoles  ? formatRoles(model.readRoles().toArray(new String[0]))
                          : hasRoles      ? formatRoles(model.roles().toArray(new String[0]))
                          : null;
        String writeRoles = hasWriteRoles ? formatRoles(model.writeRoles().toArray(new String[0]))
                          : hasRoles      ? formatRoles(model.roles().toArray(new String[0]))
                          : null;

        if (readRoles != null) {
            final String roles = readRoles;
            method.addStatement(
                "http.authorizeHttpRequests(auth -> auth"
                + "\n    .requestMatchers($T.GET, $S).hasAnyRole(" + roles + ")"
                + "\n    .requestMatchers($T.GET, $S).hasAnyRole(" + roles + ")"
                + "\n    .anyRequest().authenticated())",
                httpMethod, basePath, httpMethod, basePath + "/**");
        } else {
            method.addStatement(
                "http.authorizeHttpRequests(auth -> auth"
                + "\n    .requestMatchers($T.GET, $S).authenticated()"
                + "\n    .requestMatchers($T.GET, $S).authenticated()"
                + "\n    .anyRequest().authenticated())",
                httpMethod, basePath, httpMethod, basePath + "/**");
        }

        if (writeRoles != null) {
            final String roles = writeRoles;
            method.addStatement(
                "http.authorizeHttpRequests(auth -> auth"
                + "\n    .requestMatchers($T.POST,   $S).hasAnyRole(" + roles + ")"
                + "\n    .requestMatchers($T.PUT,    $S).hasAnyRole(" + roles + ")"
                + "\n    .requestMatchers($T.DELETE, $S).hasAnyRole(" + roles + ")"
                + "\n    .anyRequest().denyAll())",
                httpMethod, basePath,
                httpMethod, basePath + "/**",
                httpMethod, basePath + "/**");
        } else {
            method.addStatement(
                "http.authorizeHttpRequests(auth -> auth"
                + "\n    .requestMatchers($T.POST,   $S).authenticated()"
                + "\n    .requestMatchers($T.PUT,    $S).authenticated()"
                + "\n    .requestMatchers($T.DELETE, $S).authenticated()"
                + "\n    .anyRequest().denyAll())",
                httpMethod, basePath,
                httpMethod, basePath + "/**",
                httpMethod, basePath + "/**");
        }
    }

    private static String formatRoles(String[] roles) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < roles.length; i++) {
            String role = roles[i].startsWith("ROLE_") ? roles[i].substring(5) : roles[i];
            if (i > 0) sb.append(", ");
            sb.append("\"").append(role).append("\"");
        }
        return sb.toString();
    }
}
